name: ci_ingest_flights

on:
  pull_request:
    branches: [ main ]
    paths:
      - "data_extract/ingest_flights/**"

jobs:
  style:
    name: Style checks
    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: 1

    steps:
      - name: Source code - checkout PR
        uses: actions/checkout@v3

      - name: Python - initial setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Python - dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv==2023.8.23
          cd data_extract/ingest_flights
          pipenv install --system
      
      - name: Black - code formatting rules
        run: black --check --verbose --diff --color .

      - name: Unit/integration tests
        run: |
          cd data_extract/ingest_flights
          pytest

